nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@babel/helper-compilation-targets@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
  "@babel/plugin-syntax-jsx@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
  "@vue/vue3-jest@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
  babel-jest@*:
    peerDependenciesMeta:
      "@babel/core":
        optional: true
  fork-ts-checker-webpack-plugin@*:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true

yarnPath: .yarn/releases/yarn-3.1.0.cjs
